#!/bin/bash

CONF_PATH="/etc/keepalived/keepalived.conf"
MASTER_FILE="/etc/keepalived/MASTER"
NAME=$(grep -P -o 'virtual_router_id \K\w+' /etc/keepalived/keepalived.conf)

# Check if keepalived is configured on this server
# Then see if keepalived is running
if [ -s ${CONF_PATH} ]; then
	if pgrep keepalived > /dev/null 2>&1; then
		# Capture IPs within the virtual_ipaddress section
		IPS=($(sed -n "/virtual_ipaddress/,/\}/p" ${CONF_PATH} | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/'))
	else
		echo "2 Virtual_IP - Keepalived is not running on this server."
		exit
	fi
else
	exit
fi

# Check if virtual IP is assigned to this server
IP_STATS=`ip addr`
LENGTH=${#IPS[@]}
PRIMARY=0
for i in ${IPS[@]}; do
	if echo "$IP_STATS" | grep -q "$i"; then
		PRIMARY=$(($PRIMARY+1))
	fi
done

if [[ $PRIMARY -eq 0 && ! -e ${MASTER_FILE} ]]; then
	echo "0 Virtual_IP - Backup: This is the backup or secondary server of the cluster"
elif [[ $PRIMARY -eq $LENGTH && -e ${MASTER_FILE} ]]; then
	echo "0 Virtual_IP - Primary: This is the primary server of the cluster"
elif [ $PRIMARY -eq $LENGTH ]; then
	echo "2 Virtual_IP - We might a split-brian situation. Check Virtual IP on both servers"
else
	echo "2 Virtual_IP - Primary: Virtual IP is missing from this primary server"
fi

# Check if HA status has changed or not
COUNTER_PATH="/etc/keepalived/COUNTER"
if [ -s ${COUNTER_PATH} ]; then
	COUNTER=$(wc -l < $COUNTER_PATH)
	if [ $COUNTER -gt 1 ]; then
		echo "2 Virtual_Router_$NAME - The HA status has changed $COUNTER times"
	else
		echo "1 Virtual_Router_$NAME - The HA status has changed $COUNTER time"
	fi
else
	echo "0 Virtual_Router_$NAME - The HA status is stable"
fi

exit
