#!/bin/bash

#The MIT License (MIT)
#Henry Huang (http://blog.unicsolution.com)
#Most updated file: https://github.com/bbhenry/check_mk_local/edit/master/check_inode

WARN=90
CRIT=95

INODE_CHECK=`df -PTlhi -x smbfs -x tmpfs -x cifs -x iso9660 -x udf -x nfsv4 -x devtmpfs | grep -v \/mnt| sed 1d`

echo "$INODE_CHECK" | awk -v WARN=$WARN -v CRIT=$CRIT '(match($6, /[0123456789]+/)) {
	iperc= int(substr($6, RSTART, RLENGTH));
        	if (iperc < WARN )
                	print "0 Inode_Usage:"$1" IUse%="$6";"WARN"%;"CRIT"%;0%;100% OK - InodeUse%:"$6" - FStype:"$2" - Total_I:"$3" - Used_I:"$4" - Free_I:"$5" - Mounted_on:"$7;
        	else if (iperc >= WARN && iperc < CRIT)
                	{print "1 Inode_Usage:"$1" IUse%="$6";"WARN"%;"CRIT"%;0%;100% WARNING - InodeUse%:"$6" - FStype:"$2" - Total_I:"$3" - Used_I:"$4" - Free_I:"$5" - Mounted_on:"$7;}
        	else if (iperc >= CRIT)
                	{print "2 Inode_Usage:"$1" IUse%="$6";"WARN"%;"CRIT"%;0%;100% CRITICAL - InodeUse%:"$6" - FStype:"$2" - Total_I:"$3" - Used_I:"$4" - Free_I:"$5" - Mounted_on:"$7;}
}'

exit 0
